# This file contains the game code, and it imports from the function file to save space and make things simpler.

from cat_cafe_functions import *

print("Press 'enter key' after each statement to continue.")
continue_func()
print("You find yourself rising from slumber on the floor in the back room of a cafe, with no memory of who you are, or how you got there.")
continue_func()
print("You: Well, that was a bit weird.")
continue_func()
print("What should I call you by the way? I like to put name to the series of keystrokes.")
continue_func()
name = str(input("Enter your name: "))
continue_func()
print("Nice to meet you "+ name +". I like your vibe. Anyway, on with the story.")
continue_func()
print("A somewhat stern woman enters the room.")
continue_func()
print("Her: Oh, you're a bit early for your shift. Not sure how you got back here without a key...")
continue_func()
print(name + ": Wait, I'm working here? I was not informed...")
continue_func()
print("Her: My name is Nadia. I'm basically your boss. Get up, let's do your orientation...")
continue_func()
print("Nadia: So, when you're making an order, the customer will tell you what they want.")
continue_func()
print("A list of instructions will appear on your console.")
continue_func()
print("If the item is in ALL CAPS, it means you must type that particular item from their order.") 
continue_func()
print("So if you see SHAPE and someone orders circle, you would type 'circle' (no quotation marks).")
continue_func()
print("Otherwise, just type the item as is.")
continue_func()
print("Nadia: Lets do a test run.")
continue_func()
ice_water()
continue_func()
water_trial()
continue_func()
print("Nadia: Nice work! I like the touch with the parasol. You are ready for real customers!")
continue_func()

#MONDAY

print("The sun is just beginning to rise, and you are greeted by your first customer of the week.")
continue_func()
print("A Sweet Elder Woman: Oh, you must be new here. I'm Countess Florence, but you can just call me 'Flo' if that makes you more comfortable.")
continue_func()
print("Nadia: WOW! I didn't know you were a countess! What are you countess of?")
continue_func()
print("Flo: Have you ever heard of the swamp kingdom? It's a little spot down the road from here, but don't let it's humble appearances fool you. There is tremendous value in the ways of the swamp.")
continue_func()
print("... -_-")
continue_func()
matcha_latte()
continue_func()
flo_one()
print("Just after she graciously accepts her order, a new customer enters the scene. He is a tall thin man with wiry glasses and a stack of books.")
continue_func()
print("Dr. Spencer: Top of the morning! I'm the literature head at the local high school.")
continue_func() 
print(name + ": That sounds a bit formal...")
continue_func()
print("Dr. Spencer: I'm just gonna get some work done here if you don't mind.")
continue_func()
hot_tea()
continue_func()
spencer_one()
print("Kylie: just stares blankely, but not agressively. She glances furtively around the room, and upon seeing Dr. Spencer, pulls up her hoodie and tightens the drawstrings.")
continue_func()
print("Kylie: Yo, can you make boba?")
continue_func()
print("Nadia: What's Boba?")
continue_func()
print("Kylie: Ooh, a newb. Let me tell you all about it!")
continue_func()
print("...")
continue_func()
print("Nadia: So it's just flavored milk with jellies?")
continue_func()
print("Kylie: Totes.")
continue_func()
print("Nadia: I think we can handle that!")
continue_func()
boba_tea()
continue_func()
kylie_one()
print("A Rather Angry Gentleman: ...And I need those numbers on my desk at 10AM sharp. I will not tolerate any slacking off.")
continue_func()
print("Nadia: Great, Silas again. I can almost feel the terror of the person he's on the phone with.")
continue_func()
print("The man before you is the most miserable you have laid eyes upon. He might as well have actual dollar signs for eyeballs.")
continue_func()
print("Nadia: Just make him an instant coffee. He can't tell the difference anyway.")
continue_func()
coffee()
continue_func()
bus_one()
print("Your fifth customer is an ethereal looking bald man with long flowing robes.")
continue_func()
print("Traveler: This place has such a high vibrational energy that I can just feel all of my insecurites vanish.")
continue_func()
print("Now he's smelling all the plants...")
continue_func()
print("Traveler: Ooh, you guys have kombucha. I want some kombucha.")
continue_func()
print("Nadia: It's in that cooler.")
continue_func()
print("Traveler: Wait, you don't make your own kombucha?!?")
continue_func()
print("Nadia: No...")
continue_func()
print("Now the two are face to face.")
continue_func()
print("Traveler: Don't let the corporate machine take over the spirit of kombucha. I know from experience that it will destroy you.")
continue_func()
print("Nadia: That's enough. What do you want? And please order something that we actually have on the menu...")
continue_func()
smoothie()
continue_func()
trav_one()
continue_func()
print("Nadia: Monday's are usually our busiest day, and you were on sparkling form. Although, things have been changing around here...")
continue_func()

#TUESDAY

print("The sun sets, and rises once again, indicating that Tuesday has begun.")
continue_func()
print("Nadia: You slept in the back room again. You know this is a minimum wage job right?")
continue_func()
print("Flo: Hi sweetie! ;) That Matcha Latte you made me yesterday was delicious. Would you make another?")
continue_func()
matcha_latte()
continue_func()
flo_two()
continue_func()
print("Dr. Spencer: That tea you made yesterday was quite good. Here's a sticker.")
continue_func()
print("Lo and behold, there is now a large, green sticker where the center of your forehead used to be.")
continue_func()
print(name +": Thanks! I think...")
continue_func()
hot_tea()
continue_func()
spencer_two()
continue_func()
print("This time, Kylie is wearing sunglasses.")
continue_func()
print("Kylie: Yo, your boba skills are on point. If I had friends I would bring them here.")
continue_func()
print("Dr. Spencer: You might have some friends if your attitude was better.")
continue_func()
print("Kylie: Of course, you know ALL about friendship...")
continue_func()
print("Nadia: Please, not in front of the kittens...")
continue_func()
boba_tea()
continue_func()
kylie_two()
continue_func()
print("She walks right out the door with drink in hand.")
continue_func()
print("(in a passive aggressive tone) Dr. Spencer: See you in class tomorrow!")
continue_func()
print("Kylie: See you never!")
continue_func()
print("Seeing the distraught nature of your facial expression, the traveler attempts to comfort you.")
continue_func()
print("Traveler: They'll work it out I'm sure. Fighting is fleeting.")
continue_func()
smoothie()
continue_func()
trav_two()
continue_func()
print("Silas: Get me a black coffee. Pronto")
continue_func()
print("...")
coffee()
continue_func()
bus_two()

#WEDNESDAY

print("The sun sets, and rises once again, indicating that Wednesday has begun.")
continue_func()
print("Would you like a swamp secret?")
continue_func()
print("Nadia: TELL ME!")
continue_func()
print("She leans in to your ear.")
continue_func()
print(name+": ... yes? What's the secret?")
continue_func()
print("Flo: (whispering) It's secret!")
matcha_latte()
continue_func()
flo_three()
continue_func()
print("Dr. Spencer: *sniff*")
continue_func()
print("Nadia: Oh, wow. He's crying isn't he?")
continue_func()
print("Dr. Spencer: My sincerest apologies for displaying emotion. I shall do my best to remedy that.")
continue_func()
print("Nadia: No harm done!")
continue_func()
print("Dr. Spencer: My wife died last week and I'm using work to cope. Maybe that's not well advised.")
continue_func()
print("Kylie: You're not THAT irritaing. Maybe you're not irritating at all.")
continue_func()
print("Kylie: I do wish you trusted me a bit more though. Maybe if I actually did my homework...")
continue_func()
print("Nadia: Doing your homework on time is a bit extreme, don't you think?")
hot_tea()
continue_func()
spencer_three()
continue_func()
boba_tea()
continue_func()
kylie_three()
continue_func()
print("Traveler: I failed an inkblot test yesterday. Should I be concerned?")
continue_func()
print("Nadia: How do you fail an inkblot test?")
smoothie()
continue_func()
trav_three()
continue_func()
print("Silas: Black coffee. Now.")
coffee()
continue_func()
bus_three()
continue_func()
print("A beautiful woman you have never seen enters the room.")
continue_func()
print("Diva: Hi! I'd like to order a pumpkin spice latte. You make those here right?")
continue_func()
print(name + ": Well...")
continue_func()
print("Diva: Great! I'll pick it up in half an hour! See ya then.")
continue_func()
print(name+ ": We most definitely do not serve that here... What are we gonna do?")
continue_func()
print("Nadia: You must keep this absolutely secret. We are going to do something morally reprehensible.")
continue_func()
print(name+ ": I swear I will keep it absolutely secret.")
continue_func()
print("Nadia: Thank you. Hold the fort down while I'm gone.")
continue_func()
print("Now she is headed out the door.")
continue_func()
print("Nadia: Oh by the way, do you want anything from Starbucks?")
continue_func()
print("30 minutes later...")
continue_func()
print("Diva: This is perfect! It's amazing that such a small shop like this could make such a thing!")
continue_func()
print("Nadia: I am so glad you like it!")
continue_func()

#THURSDAY

print("The sun sets, and rises once again, indicating that Thursday has begun.")
continue_func()
print("Flo: Hello lovelies! Would you like to buy some pond fluff? It's great for your liver.")
continue_func()
print("Nadia: I'll need to see your pond fluff selling license.")
continue_func()
print("Flo: What? It's only some fluff!")
continue_func()
print("Nadia: Oh my gosh, I'm just messing with you.")
continue_func()
print(name+": How did I get into this mess?")
continue_func()
matcha_latte()
continue_func()
flo_four()
continue_func()
print("Dr. Spencer: Have a newspaper.")
continue_func()
print(name+": Thanks?")
hot_tea()
continue_func()
spencer_four()
continue_func()
print("Kylie: Are you going to... spill the tea?")
continue_func()
print("Dr. Spencer: If you put the effort from your insults into your papers the world would be a better place.")
continue_func()
print("Kylie: YOUR world would be a better place.")
boba_tea()
continue_func()
kylie_four()
continue_func()
print("Silas enters just after the traveler, significantly earlier than usual.")
continue_func()
print("Traveler: Hi, I'd like a ...")
continue_func()
print("Silas: Hey dumbass! I was here first.")
continue_func()
print("Traveler: I think we have different ideas about the meaning of the word 'first.'")
continue_func()
print("Nadia: (twisting hands) This should be interesting...")
continue_func()
print("Silas delivers the first punch.")
continue_func()
print("Not only does he miss, but the force of his arm drags him straight to the ground and causes injury.")
continue_func()
print("Traveler: I'll have that smoothie now :)")
continue_func()
print("Nadia: Get started on that coffee too.")
continue_func()
smoothie()
continue_func()
trav_four()
continue_func()
coffee()
continue_func()
bus_four()
continue_func()
print("Traveler: Seeing as you are quite badly injured, it seems you need this smoothie more than I do.")
continue_func()
print("Silas: Um, thanks. I guess you can have my coffee since I'm not going to work.")
continue_func()
print("Traveler: Oh, coffee is poison. I don't drink it.")
continue_func()
print("Nadia: I'll drink it!")
continue_func()
print("Diva: You got that latte from Starbucks didn't you...")
continue_func()
print("Nadia: You know, it's funny you would mention that. " +name+ " actually used to work at Starbucks!")
continue_func()
print(name + ": Yep, that's me! I definitely did use to work at Starbucks and I definitely made it myself!")
continue_func()
print("Diva: ...")
continue_func()
print("Nadia: ...")
continue_func()
print(name + ": ...")
continue_func()
print("Diva: I'll just have a ginger ale from the cooler down there.")
continue_func()

#FRIDAY

print("The sun sets, and rises once again, indicating that Friday has begun.")
continue_func()
print("Now, you're probably thinking to yourself, 'Geez, this game is called Cat Cafe. WHERE ARE THE CATS?")
continue_func()
print("Are you sure you want to find out?")
continue_func()
print(name+": Where's my boss? She's usually here by now.")
continue_func()
print("A scruffy tabby with tattered fur walks up to the counter.")
matcha_latte()
continue_func()
flo_five()
continue_func()
print("A sophisticated siamese looks up at you from the bookshelf.")
continue_func()
hot_tea()
continue_func()
spencer_five()
continue_func()
print("A small blue kitten with a rainbow streak emerges from the cooler beneath the counter.")
continue_func()
boba_tea()
continue_func()
kylie_five()
continue_func()
print("A tuxedo cat waltzes in from a limosine parked outside.")
coffee()
continue_func()
bus_five()
continue_func()
print("A lovely Persian with long golden fur and a surplus of accesories enters, only to leave just after.")
continue_func()
print("A black and white calico wakes from his nap in the catnip.")
smoothie()
continue_func()
trav_five()
continue_func()
print("It is now that you notice that his fur looks like an inkblot test.")
continue_func()
print("Has it clicked yet?")
continue_func()
print("THE END")